# Generated by Django 4.2.4 on 2023-08-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('prep_time', models.IntegerField(help_text='minutes')),
                ('cook_time', models.IntegerField(help_text='minutes')),
                ('servings', models.IntegerField()),
                ('serving_size', models.CharField(max_length=10)),
            ],
        ),
    ]
