# Generated by Django 4.2.4 on 2023-08-11 18:49

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=djrichtextfield.models.RichTextField(default=1),
            preserve_default=False,
        ),
    ]
