# Generated by Django 4.2.4 on 2023-08-11 20:56

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_category_tag_recipe_created_at_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.category'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(help_text='minutes', verbose_name='Cook Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.TextField(max_length=500, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=500, verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=djrichtextfield.models.RichTextField(verbose_name='Instructions'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Recipe Name'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(help_text='minutes', verbose_name='Prep Time (minutes)'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='serving_size',
            field=models.CharField(max_length=10, verbose_name='Serving Size'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='servings',
            field=models.IntegerField(verbose_name='Number of Servings'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='main_app.tag'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('Wi', 'White'), ('LP', 'Light Purple'), ('LB', 'Light Blue'), ('Rd', 'Red'), ('Yw', 'Yellow'), ('Gn', 'Green'), ('Or', 'Orange'), ('Pk', 'Pink'), ('Ba', 'Black'), ('Tl', 'Teal'), ('LG', 'Light Grey'), ('DG', 'Dark Grey'), ('DB', 'Dark Blue'), ('Mr', 'Maroon'), ('Gl', 'Gold'), ('DP', 'Dark Purple')], default='Wi', max_length=2, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Tag Name'),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Meal Date')),
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner'), ('S', 'Snack')], default='B', max_length=1)),
                ('recipes', models.ManyToManyField(blank=True, related_name='meals', to='main_app.recipe')),
            ],
        ),
    ]
