# Generated by Django 4.2.4 on 2023-08-13 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_recipe_category_alter_recipe_cook_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cook_time',
            field=models.IntegerField(help_text='mins', verbose_name='Cook Time'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='prep_time',
            field=models.IntegerField(help_text='mins', verbose_name='Prep Time'),
        ),
    ]
