# Generated by Django 4.2.4 on 2023-08-14 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serving', models.IntegerField(verbose_name='Amount')),
                ('serving_size', models.CharField(choices=[('TB', 'Tbsp'), ('TS', 'Tsp'), ('CP', 'Cup'), ('QT', 'Quart'), ('PT', 'Pint'), ('PC', 'Pinch'), ('WH', 'Whole'), ('SM', 'Small'), ('MD', 'Medium'), ('LG', 'Large'), ('UN', 'Unit')], default='TB', max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(to='main_app.ingredient'),
        ),
    ]
