# Generated by Django 4.2.4 on 2023-08-15 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ingredient_recipe_favorite_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='example', max_length=20, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
