# Generated by Django 4.2.4 on 2023-08-16 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_recipe_cook_time_alter_recipe_prep_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meal',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='meal',
            name='name',
            field=models.CharField(default='name', max_length=50, verbose_name='Meal Name'),
            preserve_default=False,
        ),
    ]
