# Generated by Django 4.2.4 on 2023-08-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_remove_tag_user_remove_recipe_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='category',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='favorite',
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.TextField(max_length=500, verbose_name='Ingredients'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
