# Generated by Django 4.2.4 on 2023-08-17 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_remove_recipe_category_remove_recipe_favorite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(verbose_name='Instructions'),
        ),
        migrations.DeleteModel(
            name='Photo',
        ),
    ]
